# Generated by Django 4.1.3 on 2022-11-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omg.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omg.register')),
            ],
        ),
    ]
